#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.
set -e

cd "$(dirname "$0")/.."

echo "running bootstrap"
source ~/.nvm/nvm.sh
nvm install && ./scripts/setup
