#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."
docker compose up -d && sleep 3 && npx prisma migrate dev && npm run dev
